### ISSUE TITLE
Find appropriate Favicon

### ISSUE THREAD

**Issue by schlusslicht** [spinfo/autoChirp#11]
We should consider using an appropriate Favicon instead of the Spring default. Any suggestions @geduldia @hermesj?

**Comment by hermesj** [comment]
see src/main/resources/images/autochirp.ico

**Comment by schlusslicht** [comment]
Edited and updated the favicon (477cba4d79baa1431860e3b974c9199a28c0204e) and, as we found the artist, requested his permission to use the image and suggested mentioning him in a to-come "special thanks" section on the trivia page.

**Comment by geduldia** [comment]
closed due to finished
