### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by schlusslicht** [spinfo/autoChirp#12]
Some new features should be added to the documentation, maybe even screencasts have to be redone.

**Comment by hermesj** [comment]
* copy group screencast (next year/new reference date)
* upload gdrive screencast
* reference gdrive spreadsheet that can be copied and re-filled (already have a german one here - https://docs.google.com/spreadsheets/d/1wo705qqTWUx_wwTNbDjOz2-wcE0gcAHzuZD1hSiwyPg )

**Comment by schlusslicht** [comment]
Closed with 6ac4fcfa2fb959aa235bc7a97bf1b491e68b9afd.
