### ISSUE TITLE
Offer the possibility to chain-link groups

### ISSUE THREAD

**Issue by hermesj** [spinfo/autoChirp#13]
This seems to be a bit complicated, but very nice-to-have.
Logical: A tweet should be a reply-to his predecessor tweet in the same group, if "Chain group" is activated.
Technical: Complicated; a tweet can't be scheduled before the predecessor-tweet has gone life and autoChirp knows the ID of this tweet to realize a reply-to.

**Comment by schlusslicht** [comment]
Should this be an automatic behavior, as soon as a scheduled tweet breaches the 140 character limit? Or should the user be able to add "sub-tweets" to a "main tweet", which get posted as a reply to the "main tweet"?
I guess it would be desirable to allow both and just inform the user, that his more-than-140-char-tweet was split into a chain-linked group.

**Comment by geduldia** [comment]
closed by 1cb2177
