### ISSUE TITLE
GoogleDocs SpreadSheet upload

### ISSUE THREAD

**Issue by hermesj** [spinfo/autoChirp#9]
Enable TSV-Import directly from GoogleDocs @schlusslicht

**Comment by schlusslicht** [comment]
Gathered some intel.
Easy way: Go to Your GoogleDoc/Spreadsheet, copy the URL from the suchschlitz and paste it into autoChirp, wich will use the GoogleDrive [REST API](https://developers.google.com/drive/v3/web/manage-downloads#downloading_google_documents) to pull in (*only* the first sheet of) the corresponding document as CSV and parse it.
Hard/fancy way: Implement an OAuth consumer for the GDrive API and make all the user-owned spreadsheets browsable from "within" autoChirp (not sure how deeply embeddable that API is).

**Comment by hermesj** [comment]
IMO the easy way suffices. But I think the user should share the spreadsheet to provide access from other applications (this should be mentioned in the tutorial).

**Comment by schlusslicht** [comment]
Closed by 7af7753d5e98c457637b754461a8b37d643355dc.
